name: Update flake

on:
  schedule:
    - cron: '0 0 * * 0' # weekly

jobs:
  update:
    if: github.repository == 'amadejkastelic/sekiro-tweaker'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@v15
        with:
          name: amadejkastelic
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "flake.lock: Update"

  build:
    needs: update
    uses: ./.github/workflows/build.yaml
    secrets: inherit
